### ISSUE TITLE
Generate Links to specific combinations of Outcomes

### ISSUE THREAD

**Issue by dylanyoung-dev** [Sitecore/Sitecore-Migration-Game#10]
This is complex, because there could be many combinations of outcomes, but would be great if you could have a link that would take you to a specific outcome. This would help with social marketing companions because you could talk about a specific scenario in a tweet or a blog and then have a link to that outcome.

This needs some more consideration.

**Comment by jst-cyr** [comment]
@dylanyoung-dev : Is this now complete with the latest shareable links implementation?

**Comment by dylanyoung-dev** [comment]
Yup this should be complete!
