### ISSUE TITLE
Remaining Questions field doesn't seem to update

### ISSUE THREAD

**Issue by robearlam** [Sitecore/Sitecore-Migration-Game#27]
The `Remaining Questions` field seems to always display `1`

![image](https://github.com/Sitecore/Sitecore-Migration-Game/assets/2149251/9ba6b524-711e-497a-a1db-67678016bc74)

**Comment by dylanyoung-dev** [comment]
Technically not a bug, but the functionality definitely needs improving, so created #45 to hopefully address these improvements.

**Comment by dylanyoung-dev** [comment]
Yes, we now handle via the Progress bar.
