### ISSUE TITLE
Do we always recommend Search?

### ISSUE THREAD

**Issue by robearlam** [Sitecore/Sitecore-Migration-Game#29]
Are we always recommending Search as I can't seem to get a solution that just recommends XMC on its own. It tried the simplest scenario I could think of from the options but Search is still recommended?

Answers chosen:
![image](https://github.com/Sitecore/Sitecore-Migration-Game/assets/2149251/1df2fad5-38d2-4b4a-9ac4-6c9ca7a84802)

**Comment by jst-cyr** [comment]
We now will ask the question about Search, but we still need to have logic that takes this into account for the outcome generation.

**Comment by jst-cyr** [comment]
Closed this with #36
