### ISSUE TITLE
Add Powered by Sitecore CH1 and CDP/Personalize

### ISSUE THREAD

**Issue by dylanyoung-dev** [Sitecore/Sitecore-Migration-Game#4]
Will want to market that this product/tool is built by these products. Will also likely want to create a bunch of content around these two implementations. I'm adding it in, because I don't want to forget.

**Comment by jst-cyr** [comment]
This has been added into the "Credits"/"Info" modal that displays when somebody clicks the ❔ icon. Likely needs to be more visible, but it's a first step.

**Comment by dylanyoung-dev** [comment]
Will leave open since, we need to include CDP/Personalize to this, as well as maybe include a logo like the Change Log project.  This is required for Production, but not necessarily any sooner.

**Comment by jst-cyr** [comment]
@dylanyoung-dev : Can we close this one now? Do we feel like we've done enough here?

**Comment by dylanyoung-dev** [comment]
Yeah I believe so, since this is mentioned in the about section.
